version: '3.3'

services:
  postgresql:
    image: postgres:12-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: blog
    volumes:
      - postgres-data:/var/lib/postgresql/data_blog

volumes:
  postgres-data:
    driver: local